src/objects/COVA_Project__c.object
<CustomObject>
    <fields>
        <fullName>COVA_Description__c</fullName>
        <label>COVA_Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>COVA_Opportunity__c</fullName>
        <label>COVA_Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>COVA_Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>COVA_PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>COVA_Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>COVA_Projects</relationshipLabel>
        <relationshipName>COVA_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>COVA_Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>COVA_Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/COVA_ProbabilityTriggerHandler.cls
public class COVA_ProbabilityTriggerHandler {
    
    private static COVA_ProbabilityTriggerHandler handlerInstance = new COVA_ProbabilityTriggerHandler();
    
    private COVA_ProbabilityTriggerHandler () {
        
    }

    //test comments
    
    public static COVA_ProbabilityTriggerHandler getInstance () {
        return handlerInstance;
    }
    
    public void triggerExecuting (List<Opportunity> opportunities) {
        
        List<COVA_Project__c> projects = new List<COVA_Project__c>();  
        
        Map<Id, Id> accConMap = new Map<Id,Id>();
        
        Set<String> projectsId = new Set<String>();  
        
        for(COVA_Project__c index : [SELECT Id,COVA_Opportunity__c FROM COVA_Project__c WHERE COVA_Opportunity__c != null]){
            projectsId.add(index.COVA_Opportunity__c);
        }        
        
        for(Account acc : [SELECT Id, COVA_Primarycontact__c FROM Account WHERE COVA_Primarycontact__c != null]){
            accConMap.put(acc.Id, acc.COVA_Primarycontact__c);
        }
        
        for(Opportunity opp : opportunities){            
            if(opp.Probability > 80 && !projectsId.contains(opp.Id)){
                
                COVA_Project__c projNew = new COVA_Project__c(Name = opp.Name,                                                              
                                                              COVA_Description__c = opp.Description,
                                                              COVA_Opportunity__c = opp.Id,                                                            
                                                              COVA_PrimaryContact__c = accConMap.get(opp.AccountId));
                projects.add(projNew);
            }
        } 
        
        try{
            insert projects;
        }
        
        catch(Exception e){
           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,e.getStackTraceString());
           ApexPages.addMessage(myMsg);
        }
    }
    
}