src/objects/COVA_AccountTask__c.object
<CustomObject>
    <fields>
        <fullName>COVA_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>COVA_AccountTasks</relationshipLabel>
        <relationshipName>COVA_AccountTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>COVA_IsNotToShow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>COVA_IsNotToShow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>COVA_TaskDescription__c</fullName>
        <label>COVA_TaskDescription</label>
        <type>TextArea</type>
    </fields>
    <label>COVA_AccountTask</label>
    <nameField>
        <label>COVA_AccountTask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>COVA_AccountTasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/COVA_AccountTaskApexController.cls
public with sharing class COVA_AccountTaskApexController {
    
    @AuraEnabled
    public static List<Account> getAccount(){
        List<Account> accountList = [SELECT Id, Name FROM Account WHERE OwnerId =:UserInfo.getUserId() ];//AND Name = 'KOVAL'];s        
        return accountList;
    }
    
    @AuraEnabled
    public static List<COVA_AccountTask__c> getAccountTasks(String accountId){
        System.debug('accountId = = =' + accountId);
        List<COVA_AccountTask__c> taskList = [SELECT Id, Name, COVA_TaskDescription__c FROM COVA_AccountTask__c
                                        WHERE COVA_Account__c =: accountId AND COVA_IsNotToShow__c = false];
        System.debug('taskList==' + taskList.size());
        return taskList;
    }
}