src/objects/DPS_Event__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Event_Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Event Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>DPS Event</label>
</CustomObject>

src/objects/FolioEvent__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FolioEvents</relationshipLabel>
        <relationshipName>FolioEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>FolioEvents</relationshipLabel>
        <relationshipName>FolioEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Folio Events</relationshipLabel>
        <relationshipName>FolioEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>articleStackTitle__c</fullName>
        <label>Slide Stack Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventName__c</fullName>
        <label>Event Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eventTime__c</fullName>
        <label>Event Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>issueName__c</fullName>
        <label>Presentation Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>issuerId__c</fullName>
        <label>Issuer Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>stackId__c</fullName>
        <label>Slide Stack Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FolioEvent</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>FolioEvent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FolioEvents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/postFolioEvent.cls
@RestResource(urlMapping='/postFolioEvent')
global with sharing class postFolioEvent{
 
    @HttpPost
    global static void doPost(String stackId, String issueId, String eventName, DateTime eventTime, String issueName, String articleStackTitle, 
                              String parentId
                              ){
        String opportunityId;
        String leadId;
        String accountId;
        String folioName;
        ID folioId;
                                  
        //Check for opportunity
        if(parentId.substring(0, 3) == '006' ){
            opportunityId = parentId;
        //Check for lead
        } else if(parentId.substring(0, 3) == '00Q'){
            leadId = parentId;
        //Check for account
        } else if(parentId.substring(0, 3) == '001'){
            accountId = parentId;
        }

        //Set<String> dpsEvents = DPS_Event__c.getAll().keySet();
        Set<String> selectedEvents = new Set<String>();
        for(DPS_Event__c event : DPS_Event__c.getall().values()){
            if(event.Event_Selected__c){
                selectedEvents.add(event.Name);
            }
        }

        if(selectedEvents.contains(eventName)){
            FolioEvent__c event = new FolioEvent__c(
                ArticleStackTitle__c = articleStackTitle,
                EventName__c = eventName,
                EventTime__c = eventTime,
                IssueName__c = issueName,
                IssuerId__c = issueId,
                Opportunity__c = opportunityId,
                Lead__c = leadId,
                Account__c = accountId,
                StackId__c = stackId
            );
            insert event;
        }

    }
}