src/objects/DPS__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>App_Url__c</fullName>
        <label>App Url</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Out__c</fullName>
        <description>Time out, in seconds</description>
        <label>Time Out</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DPS</label>
</CustomObject>

src/classes/SetupControllerTest.cls
@isTest
private class SetupControllerTest {
    
    @isTest static void testSetupController() {
        DPS__c dpsSettings = DPS__c.getOrgDefaults();
        dpsSettings.Time_Out__c = 30;
        dpsSettings.App_Url__c = '//v1/slot/';
        upsert dpsSettings;

        setupController controller = new SetupController();
        controller.init();
        controller.save();
        controller.selectClick();
        controller.unselectClick();
        controller.getSelectedValues();
        controller.getUnselectedValues();

        controller.upload();

        System.assertEquals('30', controller.eventTimeout);
    }
    
}