src/objects/DPS__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>App_Url__c</fullName>
        <label>App Url</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DPS_Logo__c</fullName>
        <description>DPS logo document object ID</description>
        <label>DPS Logo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folio_Conversion__c</fullName>
        <defaultValue>true</defaultValue>
        <description>A flag to set if folioEvents should be moved to Accounts on lead conversion.</description>
        <label>Folio Conversion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Time_Out__c</fullName>
        <description>Time out, in seconds</description>
        <label>Time Out</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_Period__c</fullName>
        <defaultValue>&quot;Previous FQ&quot;</defaultValue>
        <label>Time Period</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Percent__c</fullName>
        <label>Top Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>DPS</label>
</CustomObject>

src/objects/DPS_Event__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Event_Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Event Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>DPS Event</label>
</CustomObject>

src/objects/DPS_Plugin_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>DPS_Plugin_Version__c</fullName>
        <label>DPS Plugin Version</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>DPS Plugin Settings</label>
</CustomObject>

src/classes/PostInstall.cls
global without sharing class PostInstall implements InstallHandler {
    
    //Modify this variable to be the DPS plugin version number
    public Integer pluginVersion = System.requestVersion().major();

    global void onInstall(InstallContext context){
        if(context.previousVersion() == null) {

            DPS__c appSettings = DPS__c.getOrgDefaults();
            appSettings.Time_Out__c = 30;
            appSettings.Top_Percent__c = 10;
            appSettings.Time_Period__c = 'Current FY';
            appSettings.Folio_Conversion__c = false;
            /*for(Document d : [Select id,name,NamespacePrefix from Document where Type='png']){
                system.debug(d.name +':'+ d.NamespacePrefix);
                appSettings.DPS_Logo__c = d.Id;
            }*/
            appSettings.App_Url__c = 'mysfdc://v1/slot/library';
            upsert appSettings;   

            List<DPS_Event__c> eventList = new List<DPS_Event__c>();
            eventList.add(new DPS_Event__c(Name = 'App Close', Event_Selected__c = false));
            eventList.add(new DPS_Event__c(Name = 'App Startup', Event_Selected__c = false));
            eventList.add(new DPS_Event__c(Name = 'Contet Browse', Event_Selected__c = false));
            eventList.add(new DPS_Event__c(Name = 'Content Exit', Event_Selected__c = false));
            eventList.add(new DPS_Event__c(Name = 'Content View', Event_Selected__c = true));
            eventList.add(new DPS_Event__c(Name = 'End of article reached', Event_Selected__c = false));
            eventList.add(new DPS_Event__c(Name = 'Issue Download Started', Event_Selected__c = false));
            eventList.add(new DPS_Event__c(Name = 'Overlay Started', Event_Selected__c = false));
            eventList.add(new DPS_Event__c(Name = 'Overlay Stopped', Event_Selected__c = false));
            upsert eventList;
        
            try{
                System.Schedule('Update Top SalesPeople :30', '0 30 * * * ?', new TopOwnersBatch());
       
            }catch(exception ex){
       
            }
        }
        
        DPS_Plugin_Settings__c pluginSettings = DPS_Plugin_Settings__c.getOrgDefaults();
        pluginSettings.DPS_Plugin_Version__c = String.valueOf(pluginVersion);

        upsert pluginSettings;
    }

}