src/objects/PRSD_TemplateStorage__c.object
<CustomObject>
    <fields>
        <fullName>PRSD_PreviewHtml__c</fullName>
        <label>PRSD_PreviewHtml</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>PRSD_TemplateStorage</label>
    <nameField>
        <label>PRSD_TemplateStorage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRSD_TemplateStorages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PRSD_TestInvestigateController.cls
public class PRSD_TestInvestigateController {    
    
    public String htmlValue { get; set; }
    
    public PRSD_TestInvestigateController(){
       selectReference();
         }
    
    public void selectReference(){        
        //EmailTemplate candidate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE Id = '00X0Y000000sKNV']; 
        //htmlValue = candidate.HtmlValue;
        PRSD_TemplateStorage__c templ = [SELECT Id, PRSD_PreviewHtml__c FROM PRSD_TemplateStorage__c WHERE Name = 'Template1'];
        htmlValue = templ.PRSD_PreviewHtml__c;        
    }
    
    

}