src/objects/Target__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Target Customers</relationshipLabel>
        <relationshipName>Target_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Target_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Target Customer</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TourPlanning.cls
public class TourPlanning {
   public Account account = new Account();
    
    public List<Target__c> getContacts() {
        return [SELECT Customer__c FROM Target__c WHERE Representative__c = :account.Id];
    }
    
    public void setAccount(){
        this.account = [SELECT Id, Name, Site FROM Account 
                   WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
    }
}