src/objects/Target__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Target Customers</relationshipLabel>
        <relationshipName>Target_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Target_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>visit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Target Customers</relationshipLabel>
        <relationshipName>Target_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Target Customer</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VisitTriggerHandler.cls
public class VisitTriggerHandler { 
    
    public void triggerExecute(Visit__c[] visitArray){        
        //query to take valid values from Target__c
        List<Target__c> listIdCustomReference = targetInit(visitArray);

        if(listIdCustomReference.size() == 0){
            System.assert(false,'Record Customer and Representative does not exist');  
        }          
        //double loop to check all visits whith Target__c Id
          
        for(Visit__c index1 : visitArray){  
            boolean flag = true;          
            for(Target__c index2 : listIdCustomReference ){                 
                if(index1.Customer__c == index2.Customer__c && index1.Representative__c == index2.Representative__c){                 
                    flag = false;
                    break;                                  
                }
            }
            if(flag){
                System.assert(false,'Please insert correct Customer or Representative');
            }
        }     
        
    }
    
    private List<Target__c> targetInit(Visit__c [] visitArray ){       
      
           List<Id> visitsCId = new List<Id>();
           List<Id> visitsRId = new List<Id>();
        
        for(Visit__c index : visitArray){
            visitsCId.add(index.Customer__c);
            visitsRId.add(index.Representative__c); 
        }
           List<Target__c> listIdCustomReference = [SELECT Customer__c,Representative__c FROM Target__c WHERE Customer__c in:visitsCId and
                                                   Representative__c in:visitsRId];        
        return listIdCustomReference;
    }
    
}