src/objects/Target__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Target Customers</relationshipLabel>
        <relationshipName>Target_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Target_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>visit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Target Customers</relationshipLabel>
        <relationshipName>Target_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Target Customer</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>(EndDateTime__c  -  StartDateTime__c) * 24 * 60</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <label>EndDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <label>StartDateTime</label>
        <type>DateTime</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestControllerTour.cls
@isTest
public class TestControllerTour {
    static testMethod void validategetContacts(){
        test.startTest();
        ControllerTour controller = new ControllerTour();
        List<Target__c> checkList = new List<Target__c>();
        checklist = [select  Customer__c, visit__c  from Target__c where Representative__c in(select Representative__c from Visit__c)];
         System.assertEquals(controller.getContacts(), checklist);
        test.stopTest();
    }
    
    static testMethod void validatesaveMethod(){
        ControllerTour controller = new ControllerTour();
        List<Visit__c> visits = new List<Visit__c>();
        visits = [select id,StartDateTime__c, EndDateTime__c, Duration__c from Visit__c ];
        test.startTest();        
        controller.save();
        List<Visit__c>checkList = [select id,StartDateTime__c, EndDateTime__c, Duration__c from Visit__c];
        System.assertEquals(null, null);
        test.stopTest();
    }
    
    static testMethod void validatecalculateMethod(){
        ControllerTour controller = new ControllerTour();
        test.startTest();
        controller.calculate();
        System.assertEquals(null, null);
        test.stopTest();
        
    }
    
  
}